language: java
sudo: false
script: mvn clean verify

after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
